### ISSUE TITLE
Parsing Error: pyparsing.ParseException: Expected "DEFINITIONS"

### ISSUE THREAD

**Issue by twix1312** [kimgr/asn1ate#58]
I'm trying to convert an LTE specification's ASN.1 syntax into python code and ran the file (see attached zip) in pyasn1gen.py.

I received the following error:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/asn1ate/pyasn1gen.py", line 649, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/asn1ate/pyasn1gen.py", line 627, in main
    parse_tree = parser.parse_asn1(asn1def)
  File "/usr/lib/python2.7/site-packages/asn1ate/parser.py", line 40, in parse_asn1
    parse_result = grammar.parseString(asn1_definition)
  File "/usr/lib/python2.7/site-packages/pyparsing.py", line 1632, in parseString
    raise exc
pyparsing.ParseException: Expected "DEFINITIONS" (at char 195), (line:8, col:13)
```

The attached file was taken from [here](http://www.3gpp.org/ftp//Specs/archive/36_series/36.413/36413-e40.zip). I had to filter out the ASN.1 definitions and remove unwanted text.

I might have made a mistake doing that. Could you please help?
[gtp.zip](https://github.com/kimgr/asn1ate/files/1478019/gtp.zip)

**Comment by kimgr** [comment]
It might be a while until I get to this, but this: `pyparsing.ParseException: Expected "DEFINITIONS" (at char 195), (line:8, col:13)` is a good place to start. You can run your ASN.1 through http://asn1-playground.oss.com/ first, to make sure it's valid.

asn1ate does not support all of ASN.1 so there may be something that's missing, and the line/column from the error message might give a clue as to what it is.

**Comment by twix1312** [comment]
Hi,

Thanks for suggesting that link. There were some ASN errors that I've
fixed. Now the compilation of the ASN.1 file works fine at that link.

However, pyasn1.gen.py gives a new error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/asn1ate/pyasn1gen.py", line 649,
in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/asn1ate/pyasn1gen.py", line 627,
in main
    parse_tree = parser.parse_asn1(asn1def)
  File "/usr/lib/python2.7/site-packages/asn1ate/parser.py", line 40, in
parse_asn1
    parse_result = grammar.parseString(asn1_definition)
  File "/usr/lib/python2.7/site-packages/pyparsing.py", line 1632, in
parseString
    raise exc
pyparsing.ParseException: Expected "END" (at char 6111), (line:195, col:37)


Any help would be appreciated.

Thanks a bunch!

**Comment by kimgr** [comment]
So is line 195, col 37 at the end of the file? Can you upload the ASN.1 as text so I can see it?

**Comment by twix1312** [comment]
I've attached the ASN.1 as a textfile (its 6600 lines long!)

If you just want that specific portion:
FROM S1AP-Constants;


```
-- **************************************************************
--
-- Interface Elementary Procedure Class
--
-- **************************************************************

S1AP-ELEMENTARY-PROCEDURE ::= CLASS {
	&InitiatingMessage				,
	&SuccessfulOutcome							OPTIONAL,
	&UnsuccessfulOutcome						OPTIONAL,
	&procedureCode				ProcedureCode 	UNIQUE,
	&criticality				Criticality 	DEFAULT ignore
}
```

its the "{" brace after "S1AP-ELEMENTARY-PROCEDURE ::= CLASS".
[gtp.txt](https://github.com/kimgr/asn1ate/files/1481691/gtp.txt)

**Comment by kimgr** [comment]
Yeah, that explains it. asn1ate doesn't support CLASSes, and I don't really know where to start on that, so I think it's safe to assume that it won't do so unless you can spare time to work on it yourself.
